apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kiosk
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: kiosk
            port:
              number: 80
