apiVersion: apps/v1
kind: Deployment
metadata:
  name: smhiservice-deployment
  namespace: smhiservice
  labels:
    app: smhiservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smhiservice
  template:
    metadata:
      labels:
        app: smhiservice
    spec:
      containers:
      - name: smhiservice
        image: {{ .Values.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        envFrom:
        - secretRef: 
            name: smhiservice-secret
        - configMapRef:
            name: smhiservice-configmap
        volumeMounts:
          - name: smhiservice-storage
            mountPath: "/data"
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 30
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 30
          timeoutSeconds: 30
      volumes:
        - name: smhiservice-storage
          persistentVolumeClaim:
            claimName: smhiservice-claim
