apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smhiservice-claim
  namespace: smhiservice
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 2Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: smhiservice-volume
  namespace: smhiservice
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/shared/smhiservice"
