apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: smhiservice-secret
  namespace: smhiservice
spec:
  template:
    metadata:
      creationTimestamp: null
      name: smhiservice-secret
      namespace: smhiservice

