apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildversionsapi-claim
  namespace: buildversionsapi
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 2Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: buildversionsapi-volume
  namespace: buildversionsapi
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/shared/buildversionsapi"
