---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: infoservice-secret
  namespace: infoservice
spec:
  encryptedData:
    ConnectionStrings__DefaultConnection: AgBgmOYP/kDCkFFdXS7P2GioC6hYj7Ry0T1V/8ph9sD881rnBow3dpLgHrsrabU6DnqTKp74pxxJ7vI5hYCsRcyImluqEhGf7JFeCEApJIkRDMpYc7CNVp31pKKAoHZOoxBLb81ZOXeHy2PAHc7kYgw1s6mDj6XEa5xFKBnaH94N/UaDtFNnUy0vkF95BciTGH1xH2JtqRyWRZQy/H96a9kifrEP8ixGg4qSQHwPDqGqHE38CCtkn/9/Q0cSK4ItsyNW0PjTu9SxyDCukh/Yy5+zwdrSEPsPq2Nnb/zVteh+HdsGsKmBCDWG47Tw90M4U/yP+yc18tlwD+uu3M9U1FNIfjwz9yiBdZIOe1IvSuYEvstDoPH0uaHj/upCGFNEjsOqNWJwRKDmBak56PGYlkJPSujlubT5z906BujJ8FYwWWg8f4sCv1AOsOFtX7wTQvj9lqW07UAEjLKzQAgRiq2pRaWhl+Y4JIqNJMOjThhoLaY5i7YCTn9EIKa2pg0qDxfjlDj//+GqnKSwvfJaRrTL1ZrIlkOhPJ8/eTE8z+5smfdkWSnM+nucYZV/cTP08q9wpsjhGVTvBIqW7kFHha3/U3XNWOmE2A6rNNDqJtu+6NCbziWfRa1CjmiO+cKgbNJypiQ2+/+uRueWvBYO0l60LckadYj1HkpyjDSUh8Oopahxfyj5Fzd+hBFMHQRj/Dh8s51kvvFMMx081imo+V9R1hsh6hrWg2uBzTcsY6KwNF50bEB7ugQeotTH5OBdVOMKctFVvXVdC4XMnaibb8UgJmsyN1tZARHQpmHIeg==
  template:
    metadata:
      creationTimestamp: null
      name: infoservice-secret
      namespace: infoservice
