apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendarservice-deployment
  namespace: calendarservice
  labels:
    app: calendarservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calendarservice
  template:
    metadata:
      labels:
        app: calendarservice
    spec:
      containers:
      - name: calendarservice
        image: {{ .Values.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
        - secretRef: 
            name: calendarservice-secret
        - configMapRef:
            name: calendarservice-configmap
#        livenessProbe:
#          httpGet:
#            path: /healthz
#            port: http
#          initialDelaySeconds: 30
#          timeoutSeconds: 30
#        readinessProbe:
#          httpGet:
#            path: /healthz
#            port: http
#          initialDelaySeconds: 30
#          timeoutSeconds: 30
        volumeMounts:
          - name: calendarservice-storage
            mountPath: "/data"
      volumes:
        - name: calendarservice-storage
          persistentVolumeClaim:
            claimName: calendarservice-claim
