apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calendarservice-claim
  namespace: calendarservice
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 2Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: calendarservice-volume
  namespace: calendarservice
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/shared/calendarservice"
