apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adminservice-claim
  namespace: adminservice
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 2Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: adminservice-volume
  namespace: adminservice
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/shared/adminservice"
