apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: adminservice-secret
  namespace: adminservice
spec:
  template:
    metadata:
      creationTimestamp: null
      name: adminservice-secret
      namespace: adminservice

