apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice-deployment
  namespace: authservice
  labels:
    app: authservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
      - name: authservice
        image: {{ .Values.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        envFrom:
        - secretRef: 
            name: authservice-secret
        - configMapRef:
            name: authservice-configmap
        volumeMounts:
          - name: authservice-storage
            mountPath: "/data"
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 30
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 30
          timeoutSeconds: 30
      volumes:
        - name: authservice-storage
          persistentVolumeClaim:
            claimName: authservice-claim
