apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authservice-claim
  namespace: authservice
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 2Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: authservice-volume
  namespace: authservice
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/shared/authservice"
