---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authservice-secret
  namespace: authservice
spec:
  template:
    metadata:
      creationTimestamp: null
      name: authservice-secret
      namespace: authservice
