@SMHIService_HostAddress = http://localhost:5151
@ACCESS_JWT = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwOGRjODZkNC0wNTI2LTRjMmItOGFjOS02YmM0ZWNmZTkwMzUiLCJqdGkiOiJjZDdjZTNkNy1iOGU0LTQ0NmEtODMwMi0xODJhMTYzMzc4NDEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjA4ZGM4NmQ0LTA1MjYtNGMyYi04YWM5LTZiYzRlY2ZlOTAzNSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJsZW5uYXJ0QGxvY2FsIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoibGVubmFydEBsb2NhbCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6WyJVc2VyIiwiU3VwZXJBZG1pbiIsIkFkbWluIl0sImV4cCI6MTcyMDYwOTY1MiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIn0.2GbeQI8acR9XCT9XP617V3N_41hXgUkGQ10Oaq8YaXg

GET {{SMHIService_HostAddress}}/Weather/weather/
Accept: application/json
Authorization: Bearer {{ACCESS_JWT}}
###
